services:
  db:
    image: postgres:16.1
    container_name: anti_leak_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: anti_leak
    volumes:
        - anti_leak_db_data:/var/lib/postgresql/data
    ports:
        - "5432:5432"

  redis:
    image: redis:7.4
    container_name: anti_leak_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
        - redis_data:/data

  vault:
    image: hashicorp/vault:1.18
    container_name: anti_leak_vault
    restart: unless-stopped
    ports:
      - "8200:8200"
    environment:
        VAULT_DEV_ROOT_TOKEN_ID: "dev-token"
        VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
    cap_add:
      - IPC_LOCK
    volumes:
      - vault_data:/vault/file

volumes:
  anti_leak_db_data:
  redis_data:
  vault_data: